version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@form8ion/eslint-config"
    versions:
    - 1.7.10
    - 1.7.11
    - 1.7.5
    - 1.7.6
    - 1.7.7
    - 1.7.8
    - 1.7.9
  - dependency-name: "@form8ion/babel-preset"
    versions:
    - 1.6.41
    - 1.6.42
    - 1.6.43
    - 1.6.44
    - 1.6.45
    - 1.6.46
    - 1.6.47
    - 1.6.48
    - 1.6.49
    - 1.6.50
    - 1.6.51
    - 1.6.52
    - 1.6.53
    - 1.6.54
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.13.0
    - 7.13.14
    - 7.13.8
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: "@babel/node"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@form8ion/remark-lint-preset"
    versions:
    - 1.0.11
    - 1.0.12
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.2
    - 4.3.3
  - dependency-name: "@form8ion/commitlint-config"
    versions:
    - 1.0.14
    - 1.0.15
    - 1.0.16
  - dependency-name: gherkin-lint
    versions:
    - 4.1.3
    - 4.2.0
  - dependency-name: lockfile-lint
    versions:
    - 4.6.0
    - 4.6.1
  - dependency-name: remark-toc
    versions:
    - 7.1.0
  - dependency-name: ban-sensitive-files
    versions:
    - 1.9.14
  - dependency-name: "@travi/any"
    versions:
    - 2.0.15
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.7.4
    - 12.8.0
    - 12.8.1
    - 12.8.2
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.11
    - 13.0.12
    - 13.0.13
    - 13.0.14
    - 13.0.15
    - 13.0.16
    - 13.0.2
    - 13.0.3
    - 13.0.4
    - 13.0.5
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
    - 13.1.0
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
    - 13.1.6
    - 13.1.7
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
