version: "~> 1.0"
notifications:
  email: false
import:
- source: form8ion/.travis-ci:node.yml
before_install:
- openssl aes-256-cbc -K $encrypted_0bbeaa733dca_key -iv $encrypted_0bbeaa733dca_iv
  -in travis-ci-secret.json.enc -out travis-ci-secret.json -d
- curl ifconfig.co
after_success: npm run coverage:report
jobs:
  include:
  - stage: deploy
    name: Deploy the server
    if: branch = master AND type != pull_request
    before_deploy:
    - npm run build
    deploy:
      provider: gae
      cleanup: false
      keyfile: travis-ci-secret.json
      project: hapi-create-react-app
      version: "$(git rev-parse --short HEAD)"
      config: app.yaml

env:
  - SKIP_PREFLIGHT_CHECK=true
